#!/usr/bin/env npx tsx
/**
 * Embedded MCP Server Documentation Generator
 *
 * Generates .mdx documentation pages for embedded MCP servers by reading
 * tool definitions from the platform repo.
 *
 * Usage (run from platform/servers/agentic/mcp/ for TypeScript path resolution):
 *   cd ../platform/servers/agentic/mcp
 *   npx tsx /path/to/docs/scripts/generate-embedded-mcp-docs.ts                       # Generate all
 *   npx tsx /path/to/docs/scripts/generate-embedded-mcp-docs.ts --server vault         # Generate one
 *   npx tsx /path/to/docs/scripts/generate-embedded-mcp-docs.ts --changed              # Generate only changed (vs origin/main)
 *   npx tsx /path/to/docs/scripts/generate-embedded-mcp-docs.ts --changed HEAD~3       # Generate only changed (vs specific ref)
 *
 * Prerequisites:
 *   - The platform repo must be cloned alongside the docs repo at ../platform
 *   - Node.js and npx/tsx must be available
 *   - Must be run from platform/servers/agentic/mcp/ directory (for @pinkfishai/* path aliases)
 */

import * as fs from 'fs'
import * as path from 'path'
import { execSync } from 'child_process'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

// ============================================================================
// Configuration
// ============================================================================

const DOCS_ROOT = path.resolve(__dirname, '..')
const PLATFORM_ROOT = path.resolve(DOCS_ROOT, '../platform')
const EMBEDDED_SERVERS_DIR = path.join(
  PLATFORM_ROOT,
  'servers/agentic/mcp/src/servers/embedded'
)
const OUTPUT_DIR = path.join(
  DOCS_ROOT,
  'api-reference/mcp-servers/embedded'
)
const DOCS_JSON_PATH = path.join(DOCS_ROOT, 'docs.json')

const GENERATED_HEADER = `{/* Auto-generated by scripts/generate-embedded-mcp-docs.ts — do not edit manually. To regenerate: see docs/scripts/README.md */}`

/**
 * Servers to exclude from doc generation.
 * Deprecated or internal-only servers that should not have public docs.
 */
const EXCLUDED_SERVERS = new Set([
  'llm',          // deprecated
  'perplexity',   // deprecated (replaced by embedded-perplexity)
  'ocr',          // deprecated (replaced by docprocess)
  'pinkfish-utilities', // agents only, internal
  'pinkconnect',  // internal connectivity
  'workflow',     // internal
])

/**
 * Maps server `name` in available-servers.ts to the doc file slug.
 * Only needed when they differ.
 */
const NAME_TO_DOC_SLUG: Record<string, string> = {
  'embedded-anthropic': 'embedded-anthropic',
  'embedded-openai': 'embedded-openai',
  'embedded-gemini': 'embedded-gemini',
  'embedded-groq': 'embedded-groq',
  'embedded-perplexity': 'embedded-perplexity',
  'datastore-structured': 'datastore-structured',
  'web-search': 'web-search',
  'code-execution': 'code-execution',
}

/**
 * Maps server `name` to the embedded/ subdirectory containing its tools.ts.
 * Only needed when they differ.
 */
const NAME_TO_CODE_DIR: Record<string, string> = {
  'embedded-anthropic': 'anthropic',
  'embedded-openai': 'openai',
  'embedded-gemini': 'gemini',
  'embedded-groq': 'groq',
  'embedded-perplexity': 'perplexity-embedded',
  'datastore-structured': 'datastore',
  'web-search': 'search',
}

/**
 * Pages that are manually maintained and should NOT be overwritten.
 * These are kept in docs.json but not regenerated.
 */
const MANUAL_PAGES = new Set([
  'artifact-tools',  // agent built-in, not an MCP server
])

// ============================================================================
// Human-readable descriptions for embedded servers
// ============================================================================

const DESCRIPTION_OVERRIDES: Record<string, string> = {
  '3d-application': 'Generate interactive 3D model viewers (GLB/GLTF) with shareable URLs',
  'agent-management': 'Create, manage, and interact with AI agents and their conversations',
  'agent-skills': 'List, create, update, and delete agent skills that guide agent behavior',
  'audio-processing': 'Text-to-speech generation and audio/video transcription',
  'browser-automation': 'AI-powered browser automation using natural language and Playwright code execution',
  'charting': 'Deploy Chart.js visualizations to shareable URLs',
  'code-execution': 'Execute JavaScript code in a sandboxed environment with MCP tool access',
  'datastore-structured': 'Structured data storage with schemas — tables with defined columns and types',
  'datastore-unstructured': 'Unstructured key-value storage — flexible JSON documents with no schema',
  'docprocess': 'Document processing — PDF, Word, CSV, and image conversion, OCR, and AI editing',
  'email': 'Send emails with HTML/text content and attachments',
  'embedded-anthropic': 'Generate text using Claude models (embedded, no API key required)',
  'embedded-gemini': 'Generate text using Google Gemini models (embedded, no API key required)',
  'embedded-groq': 'Generate text using Groq models (embedded, no API key required)',
  'embedded-openai': 'Generate text using OpenAI GPT models (embedded, no API key required)',
  'embedded-perplexity': 'Web research using Perplexity models (embedded, no API key required)',
  'filestorage': 'File storage — upload, download, share, and manage files',
  'http-utils': 'Make HTTP requests to public APIs or through custom integrations',
  'image-processing': 'AI image generation, editing, and background removal',
  'knowledge-base': 'RAG search, document Q&A, and semantic search over uploaded documents',
  'pf-account': 'Manage organization members, invitations, permissions, personas, and sub-organizations',
  'pinkfish-sidekick': 'Visual workflow builder, execution, triggers, and sub-workflow invocation',
  'vault': 'Encrypted secrets storage and management',
  'video-processing': 'AI video generation and audio extraction',
  'weather': 'Current conditions and multi-day forecasts for any location worldwide',
  'web-application': 'Deploy HTML dashboards and web applications to shareable URLs',
  'web-scraping': 'Web scraping — extract content from URLs, crawl websites, read RSS feeds',
  'web-search': 'Web search — Google, Amazon, YouTube, flights, hotels, news, academic, and more',
}

function getDocSlug(serverName: string): string {
  return NAME_TO_DOC_SLUG[serverName] || serverName
}

function getDescription(serverName: string, rawDescription: string): string {
  return DESCRIPTION_OVERRIDES[serverName] || rawDescription
}

// ============================================================================
// Zod-to-JSON-Schema converter
// (shared logic with generate-application-mcp-docs.ts)
// ============================================================================

function zodToJsonSchema(zodSchema: any): any {
  if (!zodSchema || !zodSchema._def) {
    return { type: 'any' }
  }

  const typeName = zodSchema._def.typeName
  const description =
    zodSchema._def.description || zodSchema.description || ''

  if (typeName === 'ZodString') {
    const result: any = { type: 'string' }
    if (description) result.description = description
    return result
  }

  if (typeName === 'ZodNumber') {
    const result: any = { type: 'number' }
    if (description) result.description = description
    return result
  }

  if (typeName === 'ZodBoolean') {
    const result: any = { type: 'boolean' }
    if (description) result.description = description
    return result
  }

  if (typeName === 'ZodArray') {
    const itemSchema = zodToJsonSchema(zodSchema._def.type)
    const result: any = { type: 'array', items: itemSchema }
    if (description) result.description = description
    return result
  }

  if (typeName === 'ZodObject') {
    const shape = zodSchema._def.shape()
    const properties: Record<string, any> = {}
    for (const [key, value] of Object.entries(shape)) {
      properties[key] = zodToJsonSchema(value)
    }
    const result: any = { type: 'object', properties }
    if (description) result.description = description
    return result
  }

  if (typeName === 'ZodEnum') {
    const result: any = { type: 'string', enum: zodSchema._def.values }
    if (description) result.description = description
    return result
  }

  if (typeName === 'ZodOptional') {
    const innerSchema = zodToJsonSchema(zodSchema._def.innerType)
    if (description && !innerSchema.description) {
      return { ...innerSchema, description }
    }
    return innerSchema
  }

  if (typeName === 'ZodNullable') {
    const innerSchema = zodToJsonSchema(zodSchema._def.innerType)
    const result = { ...innerSchema, nullable: true }
    if (description && !innerSchema.description) {
      result.description = description
    }
    return result
  }

  if (typeName === 'ZodDefault') {
    const innerSchema = zodToJsonSchema(zodSchema._def.innerType)
    const result = { ...innerSchema, default: zodSchema._def.defaultValue() }
    if (description && !innerSchema.description) {
      result.description = description
    }
    return result
  }

  if (typeName === 'ZodUnion') {
    const options = zodSchema._def.options as unknown[]
    if (options && options.length > 0) {
      const oneOf = options.map((option: any) => zodToJsonSchema(option))
      const result: any = { oneOf }
      if (description) result.description = description
      return result
    }
  }

  if (typeName === 'ZodRecord') {
    const result: any = { type: 'object', additionalProperties: true }
    if (description) result.description = description
    return result
  }

  if (typeName === 'ZodNativeEnum') {
    const result: any = {
      type: 'string',
      enum: Object.values(zodSchema._def.values)
    }
    if (description) result.description = description
    return result
  }

  if (typeName === 'ZodLiteral') {
    const result: any = { type: typeof zodSchema._def.value, const: zodSchema._def.value }
    if (description) result.description = description
    return result
  }

  return {
    type: typeName?.replace('Zod', '').toLowerCase() || 'any',
    ...(description ? { description } : {})
  }
}

// ============================================================================
// Parameter extraction from Zod schemas
// ============================================================================

interface ParamInfo {
  name: string
  type: string
  required: boolean
  defaultValue: string
  description: string
}

function getZodTypeName(zodSchema: any): string {
  if (!zodSchema || !zodSchema._def) return 'any'
  const typeName = zodSchema._def.typeName

  if (typeName === 'ZodOptional') return getZodTypeName(zodSchema._def.innerType)
  if (typeName === 'ZodNullable') return getZodTypeName(zodSchema._def.innerType)
  if (typeName === 'ZodDefault') return getZodTypeName(zodSchema._def.innerType)
  if (typeName === 'ZodString') return 'string'
  if (typeName === 'ZodNumber') return 'number'
  if (typeName === 'ZodBoolean') return 'boolean'
  if (typeName === 'ZodArray') return `${getZodTypeName(zodSchema._def.type)}[]`
  if (typeName === 'ZodObject') return 'object'
  if (typeName === 'ZodEnum') return 'string'
  if (typeName === 'ZodRecord') return 'object'
  if (typeName === 'ZodNativeEnum') return 'string'
  if (typeName === 'ZodLiteral') return typeof zodSchema._def.value
  if (typeName === 'ZodUnion') return 'string'
  return 'any'
}

function isOptional(zodSchema: any): boolean {
  if (!zodSchema || !zodSchema._def) return false
  const typeName = zodSchema._def.typeName
  if (typeName === 'ZodOptional') return true
  if (typeName === 'ZodDefault') return true
  if (typeName === 'ZodNullable') return isOptional(zodSchema._def.innerType)
  return false
}

function getDefault(zodSchema: any): string {
  if (!zodSchema || !zodSchema._def) return '—'
  const typeName = zodSchema._def.typeName
  if (typeName === 'ZodDefault') {
    const val = zodSchema._def.defaultValue()
    if (val === undefined || val === null) return '—'
    if (typeof val === 'string') return `\`"${val}"\``
    return `\`${JSON.stringify(val)}\``
  }
  if (typeName === 'ZodOptional') return '—'
  if (typeName === 'ZodNullable') return getDefault(zodSchema._def.innerType)
  return '—'
}

function getZodDescription(zodSchema: any): string {
  if (!zodSchema || !zodSchema._def) return ''
  const desc = zodSchema._def.description || zodSchema.description || ''
  if (desc) return desc
  const typeName = zodSchema._def.typeName
  if (
    typeName === 'ZodOptional' ||
    typeName === 'ZodDefault' ||
    typeName === 'ZodNullable'
  ) {
    return getZodDescription(zodSchema._def.innerType)
  }
  return ''
}

function extractParams(paramsSchema: Record<string, any>): ParamInfo[] {
  const params: ParamInfo[] = []
  for (const [name, schema] of Object.entries(paramsSchema)) {
    if (name === 'PCID') continue
    params.push({
      name,
      type: getZodTypeName(schema),
      required: !isOptional(schema),
      defaultValue: getDefault(schema),
      description: getZodDescription(schema)
    })
  }
  return params
}

// ============================================================================
// MDX generation
// ============================================================================

function escapeMarkdown(str: string): string {
  return str
    .replace(/\|/g, '\\|')
    .replace(/\{/g, '&#123;')
    .replace(/\}/g, '&#125;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
}

function generateToolSection(tool: any): string {
  const params = extractParams(tool.paramsSchema || {})

  // Build inputSchema JSON from paramsSchema
  const inputSchemaObj: any = { type: 'object', properties: {} }
  const required: string[] = []
  for (const [name, schema] of Object.entries(tool.paramsSchema || {})) {
    inputSchemaObj.properties[name] = zodToJsonSchema(schema)
    if (!isOptional(schema)) {
      required.push(name)
    }
  }
  if (required.length > 0) {
    inputSchemaObj.required = required
  }

  let md = `## ${tool.name}\n\n`
  md += `${escapeMarkdown(tool.description)}\n\n`

  // Parameters table
  if (params.length > 0) {
    md += `**Parameters:**\n\n`
    md += `| Parameter | Type | Required | Default | Description |\n`
    md += `| --- | --- | --- | --- | --- |\n`
    for (const p of params) {
      md += `| \`${p.name}\` | ${p.type} | ${p.required ? 'Yes' : 'No'} | ${p.defaultValue} | ${escapeMarkdown(p.description)} |\n`
    }
    md += '\n'
  } else {
    md += `**Parameters:** None\n\n`
  }

  // Expandable inputSchema
  md += `<Expandable title="inputSchema">\n\n`
  md += '```json\n'
  md += JSON.stringify(inputSchemaObj, null, 2) + '\n'
  md += '```\n\n'
  md += `</Expandable>\n`

  return md
}

function generateServerPage(
  serverName: string,
  rawDescription: string,
  tools: any[],
  label?: string
): string {
  const docSlug = getDocSlug(serverName)
  const description = getDescription(serverName, rawDescription)
  const displayName = label || docSlug

  let md = `---\n`
  md += `title: "${displayName.replace(/"/g, '\\"')}"\n`
  md += `sidebarTitle: "${displayName.replace(/"/g, '\\"')}"\n`
  md += `description: "${description.replace(/"/g, '\\"')}"\n`
  md += `---\n\n`
  md += `${GENERATED_HEADER}\n\n`
  md += `**Server path:** \`/${serverName}\` | **Type:** Embedded | **PCID required:** No\n\n`

  // Tools table
  md += `## Tools\n\n`
  md += `| Tool | Description |\n`
  md += `| --- | --- |\n`
  for (const tool of tools) {
    md += `| [\`${tool.name}\`](#${tool.name}) | ${escapeMarkdown(tool.description)} |\n`
  }
  md += '\n---\n\n'

  // Individual tool sections
  for (let i = 0; i < tools.length; i++) {
    md += generateToolSection(tools[i])
    if (i < tools.length - 1) {
      md += '\n---\n\n'
    }
  }

  return md
}

// ============================================================================
// Server registry loading
// ============================================================================

interface ServerEntry {
  name: string
  label?: string
  description: string
  path: string
  embedded: boolean
  availableToAgents?: boolean
  availableToUsers?: boolean
  productionEnabled?: boolean
  tools: any[]
}

async function loadAvailableServers(): Promise<ServerEntry[]> {
  const availableServersPath = path.join(
    PLATFORM_ROOT,
    'servers/agentic/mcp/src/servers/available-servers.ts'
  )

  try {
    const mod = await import(availableServersPath)
    return mod.AVAILABLE_SERVERS as ServerEntry[]
  } catch (e) {
    console.error(
      'Could not import available-servers.ts directly. Ensure you are running from platform/servers/agentic/mcp/'
    )
    console.error(e)
    throw e
  }
}

function filterEmbeddedServers(servers: ServerEntry[]): ServerEntry[] {
  return servers.filter((s) => {
    if (!s.embedded) return false
    if (EXCLUDED_SERVERS.has(s.name)) return false
    // Include servers available to users OR agents (public-facing)
    if (s.availableToUsers === false && s.availableToAgents === false) return false
    return true
  })
}

// ============================================================================
// docs.json update
// ============================================================================

function updateDocsJson(serverSlugs: string[], selectiveSlugs?: string[], slugToLabel?: Map<string, string>): void {
  /** Sort page paths by their display label (falling back to slug) */
  const sortByLabel = (pages: string[]) => {
    return pages.sort((a, b) => {
      const slugA = a.split('/').pop() || a
      const slugB = b.split('/').pop() || b
      const labelA = (slugToLabel?.get(slugA) || slugA).toLowerCase()
      const labelB = (slugToLabel?.get(slugB) || slugB).toLowerCase()
      return labelA.localeCompare(labelB)
    })
  }
  const docsJson = JSON.parse(fs.readFileSync(DOCS_JSON_PATH, 'utf-8'))

  // Find the "Embedded MCP Servers" group in the navigation
  let embeddedGroup: any = null
  function findGroup(obj: any): boolean {
    if (Array.isArray(obj)) {
      for (const item of obj) {
        if (findGroup(item)) return true
      }
    } else if (obj && typeof obj === 'object') {
      if (obj.group === 'Embedded MCP Servers') {
        embeddedGroup = obj
        return true
      }
      for (const value of Object.values(obj)) {
        if (findGroup(value)) return true
      }
    }
    return false
  }
  findGroup(docsJson)

  if (!embeddedGroup) {
    console.error('Could not find "Embedded MCP Servers" group in docs.json')
    process.exit(1)
  }

  if (selectiveSlugs) {
    // Add server pages if not already present, maintaining alphabetical order
    const existingPages: string[] = embeddedGroup.pages || []
    // Preserve overview and manual pages
    const staticPages = existingPages.filter(
      (p: string) =>
        p === 'api-reference/mcp-servers/embedded/overview' ||
        [...MANUAL_PAGES].some((mp) => p === `api-reference/mcp-servers/embedded/${mp}`)
    )
    const serverPages = existingPages.filter(
      (p: string) =>
        p !== 'api-reference/mcp-servers/embedded/overview' &&
        ![...MANUAL_PAGES].some((mp) => p === `api-reference/mcp-servers/embedded/${mp}`)
    )
    for (const slug of selectiveSlugs) {
      const pagePath = `api-reference/mcp-servers/embedded/${slug}`
      if (!serverPages.includes(pagePath)) {
        serverPages.push(pagePath)
      }
    }
    embeddedGroup.pages = [
      'api-reference/mcp-servers/embedded/overview',
      ...sortByLabel(insertManualPages(serverPages))
    ]
  } else {
    // Full replacement
    const serverPages = serverSlugs.map(
      (slug) => `api-reference/mcp-servers/embedded/${slug}`
    )
    embeddedGroup.pages = [
      'api-reference/mcp-servers/embedded/overview',
      ...sortByLabel(insertManualPages(serverPages))
    ]
  }

  fs.writeFileSync(DOCS_JSON_PATH, JSON.stringify(docsJson, null, 2) + '\n')
}

/** Insert manual pages into the sorted server pages list at the correct alphabetical position */
function insertManualPages(serverPages: string[]): string[] {
  const manualEntries = [...MANUAL_PAGES]
    .map((mp) => `api-reference/mcp-servers/embedded/${mp}`)
  const combined = [...serverPages]
  for (const entry of manualEntries) {
    if (!combined.includes(entry)) {
      combined.push(entry)
    }
  }
  return combined.sort()
}

// ============================================================================
// Git-based change detection
// ============================================================================

function getChangedServers(baseRef: string): string[] {
  const embeddedPrefix = 'servers/agentic/mcp/src/servers/embedded/'
  const sandboxPrefix = 'servers/agentic/mcp/src/groups/sandbox/'

  let diffOutput: string
  try {
    diffOutput = execSync(
      `git diff ${baseRef} --name-only -- "${embeddedPrefix}" "${sandboxPrefix}"`,
      { cwd: PLATFORM_ROOT, encoding: 'utf-8' }
    ).trim()
  } catch {
    return []
  }

  const serverNames = new Set<string>()
  if (diffOutput) {
    for (const filePath of diffOutput.split('\n')) {
      if (filePath.startsWith(embeddedPrefix)) {
        const relative = filePath.replace(embeddedPrefix, '')
        const dirName = relative.split('/')[0]
        if (dirName && dirName !== 'shared') {
          // Reverse-map code dir to server name
          const serverName = codeDirToServerName(dirName)
          if (serverName) serverNames.add(serverName)
        }
      }
      if (filePath.startsWith(sandboxPrefix)) {
        serverNames.add('code-execution')
      }
    }
  }

  return Array.from(serverNames).sort()
}

/** Reverse lookup: given embedded/ subdirectory name, find the server name */
function codeDirToServerName(dirName: string): string | null {
  // Check reverse of NAME_TO_CODE_DIR
  for (const [name, dir] of Object.entries(NAME_TO_CODE_DIR)) {
    if (dir === dirName) return name
  }
  // Default: directory name is the server name
  return dirName
}

function getNewServersWithoutDocs(embeddedServers: ServerEntry[]): string[] {
  const newServers: string[] = []

  for (const server of embeddedServers) {
    const docSlug = getDocSlug(server.name)
    const docPath = path.join(OUTPUT_DIR, `${docSlug}.mdx`)
    if (!fs.existsSync(docPath)) {
      newServers.push(server.name)
    }
  }

  return newServers.sort()
}

// ============================================================================
// Main
// ============================================================================

async function main(): Promise<void> {
  const args = process.argv.slice(2)
  const serverFlagIdx = args.indexOf('--server')
  const singleServer =
    serverFlagIdx !== -1 ? args[serverFlagIdx + 1] : undefined
  const changedFlagIdx = args.indexOf('--changed')
  const changedBaseRef =
    changedFlagIdx !== -1 ? (args[changedFlagIdx + 1] || 'origin/main') : undefined

  if (singleServer && changedBaseRef) {
    console.error('Cannot use --server and --changed together.')
    process.exit(1)
  }

  console.log('=== Embedded MCP Server Documentation Generator ===\n')

  // Ensure output directory exists
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true })
  }

  // Load server registry
  let servers: ServerEntry[]
  try {
    servers = await loadAvailableServers()
  } catch {
    process.exit(1)
  }

  // Filter to embedded, non-excluded servers
  const embeddedServers = filterEmbeddedServers(servers)

  console.log(
    `Found ${embeddedServers.length} documentable embedded servers\n`
  )

  // Determine which servers to generate
  let toGenerate: ServerEntry[]
  let selectiveSlugs: string[] | undefined

  if (changedBaseRef) {
    const changedNames = getChangedServers(changedBaseRef)
    const newServerNames = getNewServersWithoutDocs(embeddedServers)

    const allTargetNames = Array.from(
      new Set([...changedNames, ...newServerNames])
    ).sort()

    if (allTargetNames.length === 0) {
      console.log(
        `No embedded server changes found compared to ${changedBaseRef}, and all servers have documentation.`
      )
      console.log('\n=== Done (nothing to generate) ===')
      return
    }

    if (changedNames.length > 0) {
      console.log(`Changed servers (vs ${changedBaseRef}): ${changedNames.join(', ')}`)
    }
    if (newServerNames.length > 0) {
      console.log(`New servers (without documentation): ${newServerNames.join(', ')}`)
    }
    console.log('')

    toGenerate = embeddedServers.filter((s) => allTargetNames.includes(s.name))
    selectiveSlugs = allTargetNames.map(getDocSlug)
    const missing = allTargetNames.filter(
      (name) => !toGenerate.some((s) => s.name === name)
    )
    if (missing.length > 0) {
      console.warn(`  Warning: changed/new but excluded or not found: ${missing.join(', ')}`)
    }
  } else if (singleServer) {
    // Allow specifying by either server name or doc slug
    toGenerate = embeddedServers.filter(
      (s) => s.name === singleServer || getDocSlug(s.name) === singleServer
    )
    if (toGenerate.length === 0) {
      console.error(`Server "${singleServer}" not found among documentable embedded servers.`)
      console.error(
        'Available:',
        embeddedServers.map((s) => s.name).join(', ')
      )
      process.exit(1)
    }
    selectiveSlugs = toGenerate.map((s) => getDocSlug(s.name))
  } else {
    toGenerate = embeddedServers
  }

  // Build slug-to-label map from all embedded servers (not just toGenerate)
  const slugToLabel = new Map<string, string>()
  for (const server of embeddedServers) {
    const slug = getDocSlug(server.name)
    if (server.label) {
      slugToLabel.set(slug, server.label)
    }
  }

  let totalTools = 0
  const generatedSlugs: string[] = []

  for (const server of toGenerate) {
    const tools = server.tools
    if (!tools || tools.length === 0) {
      console.warn(`  Skipping ${server.name}: no tools found`)
      continue
    }

    const docSlug = getDocSlug(server.name)
    console.log(
      `  Generating ${docSlug}.mdx (${tools.length} tools)...`
    )

    const mdx = generateServerPage(server.name, server.description, tools, server.label)
    const outputPath = path.join(OUTPUT_DIR, `${docSlug}.mdx`)
    fs.writeFileSync(outputPath, mdx)

    totalTools += tools.length
    generatedSlugs.push(docSlug)
  }

  // Update docs.json
  if (generatedSlugs.length > 0) {
    if (selectiveSlugs) {
      updateDocsJson(generatedSlugs, selectiveSlugs, slugToLabel)
      console.log(`\nUpdated docs.json with ${generatedSlugs.length} page(s)`)
    } else {
      updateDocsJson(generatedSlugs, undefined, slugToLabel)
      console.log(`\nUpdated docs.json with ${generatedSlugs.length} pages`)
    }
  }

  console.log(`\n=== Done ===`)
  console.log(`  Servers: ${generatedSlugs.length}`)
  console.log(`  Tools:   ${totalTools}`)
  console.log(`  Output:  ${OUTPUT_DIR}/`)
}

main().catch((e) => {
  console.error('Fatal error:', e)
  process.exit(1)
})
