#!/usr/bin/env npx tsx
/**
 * Application MCP Server Documentation Generator
 *
 * Generates .mdx documentation pages for production-enabled application (external)
 * MCP servers by reading tool definitions from the platform repo.
 *
 * Usage (run from platform/servers/agentic/mcp/ for TypeScript path resolution):
 *   cd ../platform/servers/agentic/mcp
 *   npx tsx /path/to/docs/scripts/generate-application-mcp-docs.ts                       # Generate all
 *   npx tsx /path/to/docs/scripts/generate-application-mcp-docs.ts --server slack        # Generate one classic server
 *   npx tsx /path/to/docs/scripts/generate-application-mcp-docs.ts --server genesys      # One parent page with child servers (genesys | jira-cloud | workday)
 *   npx tsx /path/to/docs/scripts/generate-application-mcp-docs.ts --changed             # Generate only changed (vs origin/main)
 *   npx tsx /path/to/docs/scripts/generate-application-mcp-docs.ts --changed HEAD~3      # Generate only changed (vs specific ref)
 *
 * Prerequisites:
 *   - The platform repo must be cloned alongside the docs repo at ../platform
 *   - Node.js and npx/tsx must be available
 *   - Must be run from platform/servers/agentic/mcp/ directory (for @pinkfishai/* path aliases)
 */

import * as fs from 'fs'
import * as path from 'path'
import { execSync } from 'child_process'
import { fileURLToPath, pathToFileURL } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

// ============================================================================
// Configuration
// ============================================================================

const DOCS_ROOT = path.resolve(__dirname, '..')
const PLATFORM_ROOT = path.resolve(DOCS_ROOT, '../platform')
const SERVERS_DIR = path.join(
  PLATFORM_ROOT,
  'servers/agentic/mcp/src/servers/external'
)
const MCP_SERVER_DEFINITIONS_DIR = path.join(
  PLATFORM_ROOT,
  'mcp-server-definitions'
)

/** How to find child-server directories under mcp-server-definitions/ */
type PartitionDiscovery =
  | { mode: 'flat-prefix'; prefix: string }
  | { mode: 'nested'; rootRelativeDir: string }

/** One Mintlify page + docs.json slug per family (merged child-server docs) */
type PartitionFamily = {
  docSlug: string
  pinkConnectService: string
  introParagraph: string
  fallbackDescription: string
  discovery: PartitionDiscovery
  /** `git diff` path prefix under the platform repo root */
  gitDiffPathPrefix: string
}

const PARTITION_FAMILIES: PartitionFamily[] = [
  {
    docSlug: 'genesys',
    pinkConnectService: 'genesys',
    introParagraph:
      'Genesys Cloud is exposed as multiple MCP server IDs (one per area below). Each child server has its own server path and tool names.',
    fallbackDescription: 'Genesys Cloud application MCP tools',
    discovery: { mode: 'nested', rootRelativeDir: 'genesys' },
    gitDiffPathPrefix: 'mcp-server-definitions/genesys/'
  },
  {
    docSlug: 'jira-cloud',
    pinkConnectService: 'jira',
    introParagraph:
      'Jira Cloud is exposed as multiple MCP server IDs (one per area below). Each child server has its own server path and tool names.',
    fallbackDescription: 'Jira Cloud application MCP tools',
    discovery: { mode: 'nested', rootRelativeDir: 'jira-cloud' },
    gitDiffPathPrefix: 'mcp-server-definitions/jira-cloud/'
  },
  {
    docSlug: 'workday',
    pinkConnectService: 'workday',
    introParagraph:
      'Workday is exposed as multiple MCP server IDs (one per functional area below). Each child server has its own server path and tool names.',
    fallbackDescription: 'Workday application MCP tools',
    discovery: { mode: 'nested', rootRelativeDir: 'workday' },
    gitDiffPathPrefix: 'mcp-server-definitions/workday/'
  }
]

const PARTITION_DOC_SLUG_SET = new Set(
  PARTITION_FAMILIES.map((f) => f.docSlug)
)

const OUTPUT_DIR = path.join(
  DOCS_ROOT,
  'api-reference/mcp-servers/application'
)
const DOCS_JSON_PATH = path.join(DOCS_ROOT, 'docs.json')

const GENERATED_HEADER = `{/* Auto-generated by scripts/generate-application-mcp-docs.ts — do not edit manually. To regenerate: see docs/scripts/README.md */}`

// ============================================================================
// Human-readable descriptions for application servers
// Overrides the terse descriptions from available-servers.ts (e.g. "Slack API" → better)
// ============================================================================

// Name overrides for display purposes (server directory name -> display name)
const NAME_OVERRIDES: Record<string, string> = {
  inform3: 'Infor M3',
  genesys: 'Genesys',
  jira: 'Jira',
  'jira-cloud': 'Jira Cloud',
  workday: 'Workday'
}

/** Classic application servers documented for backwards compatibility — marked in MDX. */
const LEGACY_CLASSIC_SERVER_DOC: Record<
  string,
  { titleSuffix: string; warningMdx: string }
> = {
  jira: {
    titleSuffix: ' (legacy)',
    warningMdx:
      'This monolithic `/jira` application server is **legacy**. For new integrations, use the [Jira Cloud](/api-reference/mcp-servers/application/jira-cloud) page and its child server paths (`/jira-issues`, `/jira-projects`, `/jira-users`).'
  }
}

const DESCRIPTION_OVERRIDES: Record<string, string> = {
  'slack': 'Channels, messages, reactions, users, and workspace management',
  'gmail': 'Email send, read, search, and label management',
  'google-drive': 'File storage, folders, permissions, and sharing',
  'google-sheets': 'Spreadsheet read, write, and formatting',
  'google-calendar': 'Events, calendars, and attendees',
  'google-docs': 'Document creation and editing',
  'google-forms': 'Form creation and response management',
  'google-maps': 'Geocoding, directions, and places',
  'google-bigquery': 'SQL queries, datasets, and tables',
  'google-slides': 'Presentation creation and editing',
  'google-iam': 'Identity and access management',
  'google-task': 'Task lists and task management',
  'google-workspace-admin': 'User and group administration',
  'microsoft-outlook': 'Email, calendar, and contacts',
  'microsoft-excel': 'Workbook and worksheet operations',
  'microsoft-powerpoint': 'Presentation operations',
  'microsoft-powerbi': 'Reports, datasets, and dashboards',
  'microsoft-teams': 'Channels, messages, and meetings',
  'microsoft-word': 'Document operations',
  'microsoft-active-directory': 'Users, groups, and directory management',
  'onedrive': 'File storage and sharing',
  'sharepoint': 'Sites, lists, and document libraries',
  'dynamics-crm': 'Accounts, contacts, leads, and opportunities',
  'salesforce': 'Objects, queries, records, and reports',
  'salesforce-sandbox': 'Sandbox environment for development and testing',
  'hubspot': 'Contacts, deals, companies, and pipelines',
  'zoho': 'CRM records and modules',
  'zoom': 'Meetings, recordings, and participants',
  'docusign': 'Envelopes, signing, and templates',
  'zendesk': 'Tickets, users, and organizations',
  'servicenow': 'Incidents, requests, and workflows',
  'freshdesk': 'Tickets, contacts, and agents',
  'snowflake': 'SQL queries, warehouses, and databases',
  'databricks': 'Notebooks, jobs, and clusters',
  'tableau': 'Workbooks, views, and data sources',
  'amplitude':
    'Amplitude Analytics — event segmentation, funnels, retention, cohorts, taxonomy, and real-time data',
  'airtable': 'Bases, tables, and records',
  'monday': 'Boards, items, and columns',
  'notion': 'Pages, databases, and blocks',
  'confluence': 'Spaces, pages, and content',
  'jira': 'Issues, projects, and boards',
  'jira-itsm': 'IT service management',
  'jira-forms': 'Form management',
  'linear': 'Issues, projects, and cycles',
  'asana': 'Tasks, projects, and workspaces',
  'smartsheet': 'Sheets, rows, and columns',
  'shopify': 'Products, orders, and customers',
  'stripe': 'Payments, subscriptions, and customers',
  'github': 'Repos, issues, and pull requests',
  'twilio': 'SMS, voice, and messaging',
  'openai': 'Chat completions, embeddings, and images',
  'anthropic': 'Claude models',
  'gemini': 'Google AI models',
  'deepgram': 'Speech-to-text and text-to-speech',
  'linkedin': 'Profile, posts, and connections',
  'linkedin-marketing': 'Ad campaigns and analytics',
  'sendgrid': 'Email campaigns and contacts',
  'dropbox': 'Files, folders, and sharing',
  'box': 'Files, folders, and collaborations',
  'amazon-s3': 'Buckets, objects, and presigned URLs',
  'azure-storage': 'Blobs, containers, and queues',
  'postgresql': 'SQL queries and schema management',
  'redis': 'Key-value operations',
  'figma': 'Design files and components',
  'gong': 'Revenue intelligence and call recordings',
  'fireflies': 'Meeting transcription',
  'greenhouse': 'Recruiting and hiring',
  'okta': 'Identity and access management',
  'kandji': 'Apple device management',
  'jamf': 'Apple device management',
  'sophos': 'Endpoint security',
  'airwatch': 'Enterprise mobility management',
  'snipeit': 'IT asset management',
  'hyperproof': 'Compliance management',
  'akeneo': 'Product information management',
  'responsiveio': 'RFP response management',
  'apify': 'Web scraping and automation',
  'brightdata': 'Web data collection',
  'polygon-io': 'Financial market data',
  'gamma': 'AI-powered presentation generation',
  'sftp-ftp': 'Secure file transfer (SFTP and FTP)',
  'faire': 'Wholesale marketplace',
  'iterable': 'Marketing analytics',
  'apollo': 'Prospecting and enrichment',
  'commercetools': 'Products, customers, orders, carts, and inventory',
  'mssql': 'Microsoft SQL Server queries and schema management',
  'mysql': 'MySQL database queries and schema management',
  'onenote': 'Notebooks, pages, and content management',
  'twitter': 'Tweets, users, timelines, and media',
  'quickbase': 'Applications, tables, records, and fields',
  'freshservice': 'IT service management tickets, assets, and agents',
  'sirv': 'Image CDN upload, management, and statistics',
  'talkdesk': 'Contact center agents, calls, queues, and recordings',
  genesys:
    'Genesys Cloud — conversations, users, routing, analytics, knowledge, contacts, workforce, tasks, and quality APIs (parent server with child servers)',
  'jira-cloud':
    'Jira Cloud — users, projects, and issues APIs (parent server with child servers)',
  workday:
    'Workday — HCM, payroll, compensation, finance, and related APIs (parent server with child servers)'
}

function getDisplayName(serverName: string): string {
  return NAME_OVERRIDES[serverName] || serverName
}

function getSidebarTitle(serverName: string, titleSuffix = ''): string {
  return `${serverName}${titleSuffix}`
}

function getDescription(serverName: string, rawDescription: string): string {
  return DESCRIPTION_OVERRIDES[serverName] || rawDescription
}

// ============================================================================
// Zod-to-JSON-Schema converter (adapted from platform/servers/agentic/mcp/src/services/server-selector.ts)
// ============================================================================

function zodToJsonSchema(zodSchema: any): any {
  if (!zodSchema || !zodSchema._def) {
    return { type: 'any' }
  }

  const typeName = zodSchema._def.typeName
  const description =
    zodSchema._def.description || zodSchema.description || ''

  if (typeName === 'ZodString') {
    const result: any = { type: 'string' }
    if (description) result.description = description
    return result
  }

  if (typeName === 'ZodNumber') {
    const result: any = { type: 'number' }
    if (description) result.description = description
    return result
  }

  if (typeName === 'ZodBoolean') {
    const result: any = { type: 'boolean' }
    if (description) result.description = description
    return result
  }

  if (typeName === 'ZodArray') {
    const itemSchema = zodToJsonSchema(zodSchema._def.type)
    const result: any = { type: 'array', items: itemSchema }
    if (description) result.description = description
    return result
  }

  if (typeName === 'ZodObject') {
    const shape = zodSchema._def.shape()
    const properties: Record<string, any> = {}
    for (const [key, value] of Object.entries(shape)) {
      properties[key] = zodToJsonSchema(value)
    }
    const result: any = { type: 'object', properties }
    if (description) result.description = description
    return result
  }

  if (typeName === 'ZodEnum') {
    const result: any = { type: 'string', enum: zodSchema._def.values }
    if (description) result.description = description
    return result
  }

  if (typeName === 'ZodOptional') {
    const innerSchema = zodToJsonSchema(zodSchema._def.innerType)
    if (description && !innerSchema.description) {
      return { ...innerSchema, description }
    }
    return innerSchema
  }

  if (typeName === 'ZodNullable') {
    const innerSchema = zodToJsonSchema(zodSchema._def.innerType)
    const result = { ...innerSchema, nullable: true }
    if (description && !innerSchema.description) {
      result.description = description
    }
    return result
  }

  if (typeName === 'ZodDefault') {
    const innerSchema = zodToJsonSchema(zodSchema._def.innerType)
    const result = { ...innerSchema, default: zodSchema._def.defaultValue() }
    if (description && !innerSchema.description) {
      result.description = description
    }
    return result
  }

  if (typeName === 'ZodUnion') {
    const options = zodSchema._def.options as unknown[]
    if (options && options.length > 0) {
      const oneOf = options.map((option: any) => zodToJsonSchema(option))
      const result: any = { oneOf }
      if (description) result.description = description
      return result
    }
  }

  if (typeName === 'ZodRecord') {
    const result: any = { type: 'object', additionalProperties: true }
    if (description) result.description = description
    return result
  }

  if (typeName === 'ZodNativeEnum') {
    const result: any = {
      type: 'string',
      enum: Object.values(zodSchema._def.values)
    }
    if (description) result.description = description
    return result
  }

  if (typeName === 'ZodLiteral') {
    const result: any = { type: typeof zodSchema._def.value, const: zodSchema._def.value }
    if (description) result.description = description
    return result
  }

  return {
    type: typeName?.replace('Zod', '').toLowerCase() || 'any',
    ...(description ? { description } : {})
  }
}

// ============================================================================
// Parameter extraction from Zod schemas
// ============================================================================

interface ParamInfo {
  name: string
  type: string
  required: boolean
  defaultValue: string
  description: string
}

function getZodTypeName(zodSchema: any): string {
  if (!zodSchema || !zodSchema._def) return 'any'
  const typeName = zodSchema._def.typeName

  if (typeName === 'ZodOptional') return getZodTypeName(zodSchema._def.innerType)
  if (typeName === 'ZodNullable') return getZodTypeName(zodSchema._def.innerType)
  if (typeName === 'ZodDefault') return getZodTypeName(zodSchema._def.innerType)
  if (typeName === 'ZodString') return 'string'
  if (typeName === 'ZodNumber') return 'number'
  if (typeName === 'ZodBoolean') return 'boolean'
  if (typeName === 'ZodArray') return `${getZodTypeName(zodSchema._def.type)}[]`
  if (typeName === 'ZodObject') return 'object'
  if (typeName === 'ZodEnum') return 'string'
  if (typeName === 'ZodRecord') return 'object'
  if (typeName === 'ZodNativeEnum') return 'string'
  if (typeName === 'ZodLiteral') return typeof zodSchema._def.value
  if (typeName === 'ZodUnion') return 'string'
  return 'any'
}

function isOptional(zodSchema: any): boolean {
  if (!zodSchema || !zodSchema._def) return false
  const typeName = zodSchema._def.typeName
  if (typeName === 'ZodOptional') return true
  if (typeName === 'ZodDefault') return true // has a default, so effectively optional
  if (typeName === 'ZodNullable') return isOptional(zodSchema._def.innerType)
  return false
}

function getDefault(zodSchema: any): string {
  if (!zodSchema || !zodSchema._def) return '—'
  const typeName = zodSchema._def.typeName
  if (typeName === 'ZodDefault') {
    const val = zodSchema._def.defaultValue()
    if (val === undefined || val === null) return '—'
    if (typeof val === 'string') return `\`"${val}"\``
    return `\`${JSON.stringify(val)}\``
  }
  if (typeName === 'ZodOptional') return '—'
  if (typeName === 'ZodNullable') return getDefault(zodSchema._def.innerType)
  return '—'
}

function getZodDescription(zodSchema: any): string {
  if (!zodSchema || !zodSchema._def) return ''
  // Walk through wrappers to find the description
  const desc = zodSchema._def.description || zodSchema.description || ''
  if (desc) return desc
  const typeName = zodSchema._def.typeName
  if (
    typeName === 'ZodOptional' ||
    typeName === 'ZodDefault' ||
    typeName === 'ZodNullable'
  ) {
    return getZodDescription(zodSchema._def.innerType)
  }
  return ''
}

function extractParams(paramsSchema: Record<string, any>): ParamInfo[] {
  const params: ParamInfo[] = []
  for (const [name, schema] of Object.entries(paramsSchema)) {
    if (name === 'PCID') continue // Skip PCID — documented in overview
    params.push({
      name,
      type: getZodTypeName(schema),
      required: !isOptional(schema),
      defaultValue: getDefault(schema),
      description: getZodDescription(schema)
    })
  }
  return params
}

// ============================================================================
// MDX generation
// ============================================================================

function escapeMarkdown(str: string): string {
  // Escape characters that MDX parses as JSX:
  //   { } → HTML entities (JSX expressions)
  //   < > → HTML entities (prevents JSX tag parsing, e.g. <Drive>, <tenant>)
  //   | → backslash escape (markdown table delimiter)
  return str
    .replace(/\|/g, '\\|')
    .replace(/\{/g, '&#123;')
    .replace(/\}/g, '&#125;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
}

function generateToolSection(tool: any): string {
  const params = extractParams(tool.paramsSchema || {})

  // Build inputSchema JSON from paramsSchema
  const inputSchemaObj: any = { type: 'object', properties: {} }
  const required: string[] = []
  for (const [name, schema] of Object.entries(tool.paramsSchema || {})) {
    inputSchemaObj.properties[name] = zodToJsonSchema(schema)
    if (!isOptional(schema)) {
      required.push(name)
    }
  }
  if (required.length > 0) {
    inputSchemaObj.required = required
  }

  let md = `## ${tool.name}\n\n`
  md += `${escapeMarkdown(tool.description)}\n\n`

  // Parameters table
  if (params.length > 0) {
    md += `**Parameters:**\n\n`
    md += `| Parameter | Type | Required | Default | Description |\n`
    md += `| --- | --- | --- | --- | --- |\n`
    for (const p of params) {
      md += `| \`${p.name}\` | ${p.type} | ${p.required ? 'Yes' : 'No'} | ${p.defaultValue} | ${escapeMarkdown(p.description)} |\n`
    }
    md += '\n'
  }

  // Expandable inputSchema
  md += `<Expandable title="inputSchema">\n\n`
  md += '```json\n'
  md += JSON.stringify(inputSchemaObj, null, 2) + '\n'
  md += '```\n\n'
  md += `</Expandable>\n`

  return md
}

function generateServerPage(
  serverName: string,
  rawDescription: string,
  tools: any[]
): string {
  const displayName = getDisplayName(serverName)
  const description = getDescription(serverName, rawDescription)
  const legacy = LEGACY_CLASSIC_SERVER_DOC[serverName]
  const titledName = `${displayName}${legacy?.titleSuffix ?? ''}`
  const descriptionForMeta = legacy
    ? `${description} (legacy)`
    : description

  let md = `---\n`
  md += `title: "${titledName.replace(/"/g, '\\"')}"\n`
  md += `sidebarTitle: "${getSidebarTitle(serverName, legacy?.titleSuffix ?? '').replace(/"/g, '\\"')}"\n`
  md += `description: "${descriptionForMeta.replace(/"/g, '\\"')}"\n`
  md += `---\n\n`
  md += `${GENERATED_HEADER}\n\n`
  if (legacy) {
    md += `<Warning>\n\n${legacy.warningMdx}\n\n</Warning>\n\n`
  }
  md += `**Server path:** \`/${serverName}\` | **Type:** Application | **PCID required:** Yes\n\n`
  // Summary/description is only in frontmatter so Mintlify meta + page body are not duplicated.

  // Tools table
  md += `## Tools\n\n`
  md += `| Tool | Description |\n`
  md += `| --- | --- |\n`
  for (const tool of tools) {
    md += `| [\`${tool.name}\`](#${tool.name}) | ${escapeMarkdown(tool.description)} |\n`
  }
  md += '\n---\n\n'

  // Individual tool sections
  for (let i = 0; i < tools.length; i++) {
    md += generateToolSection(tools[i])
    if (i < tools.length - 1) {
      md += '\n---\n\n'
    }
  }

  return md
}

// ============================================================================
// Partitioned families (mcp-server-definitions) — one merged Mintlify page each
// ============================================================================

type DefinitionPartition = {
  id: string
  description: string
  absPath: string
}

type DefinitionPartitionWithTools = DefinitionPartition & {
  tools: { name: string; description: string; inputSchema: any }[]
}

function parseMcpServerTs(src: string): { id: string; description: string } | null {
  const idM = src.match(/\bid:\s*'([^']*)'/)
  if (!idM) return null
  const descM = src.match(/\bdescription:\s*'([^']*)'/)
  return { id: idM[1], description: descM?.[1] ?? '' }
}

function discoverPartitionMetas(family: PartitionFamily): DefinitionPartition[] {
  if (!fs.existsSync(MCP_SERVER_DEFINITIONS_DIR)) return []
  const disc = family.discovery
  const out: DefinitionPartition[] = []

  if (disc.mode === 'flat-prefix') {
    for (const ent of fs.readdirSync(MCP_SERVER_DEFINITIONS_DIR, {
      withFileTypes: true
    })) {
      if (!ent.isDirectory() || !ent.name.startsWith(disc.prefix)) continue
      const absPath = path.join(MCP_SERVER_DEFINITIONS_DIR, ent.name)
      const serverTs = path.join(absPath, 'server.ts')
      const toolsDir = path.join(absPath, 'tools')
      if (!fs.existsSync(serverTs) || !fs.existsSync(toolsDir)) continue
      const meta = parseMcpServerTs(fs.readFileSync(serverTs, 'utf-8'))
      if (meta) out.push({ ...meta, absPath })
    }
  } else {
    const root = path.join(MCP_SERVER_DEFINITIONS_DIR, disc.rootRelativeDir)
    if (!fs.existsSync(root)) return []
    for (const ent of fs.readdirSync(root, { withFileTypes: true })) {
      if (!ent.isDirectory()) continue
      const absPath = path.join(root, ent.name)
      const serverTs = path.join(absPath, 'server.ts')
      const toolsDir = path.join(absPath, 'tools')
      if (!fs.existsSync(serverTs) || !fs.existsSync(toolsDir)) continue
      const meta = parseMcpServerTs(fs.readFileSync(serverTs, 'utf-8'))
      if (meta) out.push({ ...meta, absPath })
    }
  }

  return out.sort((a, b) => a.id.localeCompare(b.id))
}

async function loadDynamicToolDefinition(
  absPath: string
): Promise<{ name: string; description: string; inputSchema: any } | null> {
  try {
    const mod = (await import(pathToFileURL(absPath).href)) as { default?: any }
    const t = mod.default
    if (!t || typeof t.name !== 'string' || !t.inputSchema) return null
    return {
      name: t.name,
      description: typeof t.description === 'string' ? t.description : '',
      inputSchema: t.inputSchema
    }
  } catch (e) {
    console.warn(`  Warning: could not import tool ${absPath}: ${e}`)
    return null
  }
}

async function loadToolsForPartitionDir(
  partitionAbsBase: string
): Promise<{ name: string; description: string; inputSchema: any }[]> {
  const toolsDir = path.join(partitionAbsBase, 'tools')
  if (!fs.existsSync(toolsDir)) return []
  const files = fs
    .readdirSync(toolsDir)
    .filter((f) => f.endsWith('.ts'))
    .sort()
  const loaded: { name: string; description: string; inputSchema: any }[] = []
  for (const f of files) {
    const tool = await loadDynamicToolDefinition(path.join(toolsDir, f))
    if (tool) loaded.push(tool)
  }
  return loaded.sort((a, b) => a.name.localeCompare(b.name))
}

function jsonSchemaTypeLabel(prop: any): string {
  if (prop == null || typeof prop !== 'object') return 'any'
  if (prop.type === 'array') {
    return `${jsonSchemaTypeLabel(prop.items)}[]`
  }
  if (Array.isArray(prop.type)) return prop.type.join(' | ')
  if (typeof prop.type === 'string') return prop.type
  if (prop.properties) return 'object'
  if (prop.oneOf || prop.anyOf) return 'union'
  return 'object'
}

function extractParamsFromJsonSchema(inputSchema: {
  properties?: Record<string, any>
  required?: string[]
}): ParamInfo[] {
  const props = inputSchema.properties ?? {}
  const req = new Set(inputSchema.required ?? [])
  const params: ParamInfo[] = []
  for (const [name, schema] of Object.entries(props)) {
    if (name === 'PCID') continue
    const defVal =
      schema &&
      typeof schema === 'object' &&
      'default' in schema &&
      (schema as { default: unknown }).default !== undefined
        ? `\`${JSON.stringify((schema as { default: unknown }).default)}\``
        : '—'
    params.push({
      name,
      type: jsonSchemaTypeLabel(schema),
      required: req.has(name),
      defaultValue: defVal,
      description:
        schema &&
        typeof schema === 'object' &&
        typeof (schema as { description?: string }).description === 'string'
          ? (schema as { description: string }).description
          : ''
    })
  }
  return params
}

function generateToolSectionFromJsonSchema(tool: {
  name: string
  description: string
  inputSchema: any
}): string {
  const params = extractParamsFromJsonSchema(tool.inputSchema || {})

  let md = `## ${tool.name}\n\n`
  md += `${escapeMarkdown(tool.description)}\n\n`

  if (params.length > 0) {
    md += `**Parameters:**\n\n`
    md += `| Parameter | Type | Required | Default | Description |\n`
    md += `| --- | --- | --- | --- | --- |\n`
    for (const p of params) {
      md += `| \`${p.name}\` | ${p.type} | ${p.required ? 'Yes' : 'No'} | ${p.defaultValue} | ${escapeMarkdown(p.description)} |\n`
    }
    md += '\n'
  }

  md += `<Expandable title="inputSchema">\n\n`
  md += '```json\n'
  md += `${JSON.stringify(tool.inputSchema, null, 2)}\n`
  md += '```\n\n'
  md += `</Expandable>\n`

  return md
}

async function buildPartitionsWithToolsForFamily(
  family: PartitionFamily
): Promise<DefinitionPartitionWithTools[]> {
  const metas = discoverPartitionMetas(family)
  const filled: DefinitionPartitionWithTools[] = []
  for (const m of metas) {
    const tools = await loadToolsForPartitionDir(m.absPath)
    if (tools.length === 0) continue
    filled.push({ id: m.id, description: m.description, absPath: m.absPath, tools })
  }
  return filled
}

function mcpPartitionFamilyDefinitionsChanged(
  baseRef: string,
  gitDiffPathPrefix: string
): boolean {
  try {
    const diffOutput = execSync(`git diff ${baseRef} --name-only`, {
      cwd: PLATFORM_ROOT,
      encoding: 'utf-8'
    }).trim()
    if (!diffOutput) return false
    return diffOutput
      .split('\n')
      .some((line) => line.startsWith(gitDiffPathPrefix))
  } catch {
    return false
  }
}

async function syncPartitionedFamilyDocPage(
  family: PartitionFamily
): Promise<boolean> {
  const partitions = await buildPartitionsWithToolsForFamily(family)
  const outPath = path.join(OUTPUT_DIR, `${family.docSlug}.mdx`)

  if (partitions.length === 0) {
    if (fs.existsSync(outPath)) {
      fs.unlinkSync(outPath)
      console.log(
        `  Removed ${family.docSlug}.mdx (no partitions for family "${family.docSlug}")`
      )
    } else {
      console.log(
        `  No partitions for family "${family.docSlug}" — skipping ${family.docSlug}.mdx`
      )
    }
    return false
  }

  const title = getDisplayName(family.docSlug)
  const description = getDescription(
    family.docSlug,
    family.fallbackDescription
  )

  let md = `---\n`
  md += `title: "${title}"\n`
  md += `sidebarTitle: "${family.docSlug}"\n`
  md += `description: "${description.replace(/"/g, '\\"')}"\n`
  md += `---\n\n`
  md += `${GENERATED_HEADER}\n\n`
  md += `**PinkConnect service:** \`${family.pinkConnectService}\` | **Type:** Application (parent with child servers) | **PCID required:** Yes\n\n`
  md += `${family.introParagraph}\n\n`

  md += `## Child servers\n\n`
  md += `| Child server | Server path | Tools | Description |\n`
  md += `| --- | --- | --- | --- |\n`
  for (const p of partitions) {
    md += `| [${escapeMarkdown(p.id)}](#${p.id}) | \`/${p.id}\` | ${p.tools.length} | ${escapeMarkdown(p.description)} |\n`
  }
  md += '\n'

  for (const p of partitions) {
    md += `\n---\n\n## ${p.id}\n\n`
    md += `${escapeMarkdown(p.description)}\n\n`
    md += `**Server path:** \`/${p.id}\` | **Type:** Application | **PCID required:** Yes\n\n`

    md += `### Tools\n\n`
    md += `| Tool | Description |\n`
    md += `| --- | --- |\n`
    for (const t of p.tools) {
      md += `| [\`${t.name}\`](#${t.name}) | ${escapeMarkdown(t.description)} |\n`
    }

    for (const t of p.tools) {
      md += '\n---\n\n'
      md += generateToolSectionFromJsonSchema(t)
    }
  }

  fs.writeFileSync(outPath, md)
  const totalTools = partitions.reduce((acc, part) => acc + part.tools.length, 0)
  console.log(
    `  Generating ${family.docSlug}.mdx (${partitions.length} partitions, ${totalTools} tools)...`
  )
  return true
}

function shouldSyncPartitionedFamily(
  family: PartitionFamily,
  opts: { singleServer?: string; changedBaseRef?: string }
): boolean {
  if (opts.singleServer) {
    return opts.singleServer === family.docSlug
  }
  if (opts.changedBaseRef) {
    return mcpPartitionFamilyDefinitionsChanged(
      opts.changedBaseRef,
      family.gitDiffPathPrefix
    )
  }
  return true
}

// ============================================================================
// Server registry loading
// ============================================================================

interface ServerEntry {
  name: string
  description: string
  path: string
  embedded: boolean
  productionEnabled?: boolean
  tools: any[]
}

async function loadAvailableServers(): Promise<ServerEntry[]> {
  // Dynamically import available-servers.ts from the platform repo
  // This requires running with tsx which handles TypeScript + path aliases
  const availableServersPath = path.join(
    PLATFORM_ROOT,
    'servers/agentic/mcp/src/servers/available-servers.ts'
  )

  try {
    const mod = await import(availableServersPath)
    return mod.AVAILABLE_SERVERS as ServerEntry[]
  } catch (e) {
    // If direct import fails (path aliases), fall back to loading tool files individually
    console.error(
      'Could not import available-servers.ts directly. Falling back to file-based loading.'
    )
    console.error(e)
    throw e
  }
}

async function loadToolsForServer(
  serverName: string
): Promise<any[] | null> {
  const toolsPath = path.join(SERVERS_DIR, serverName, 'tools.ts')
  if (!fs.existsSync(toolsPath)) {
    console.warn(`  Warning: No tools.ts found for ${serverName}`)
    return null
  }
  try {
    const mod = await import(toolsPath)
    return mod.TOOLS || null
  } catch (e) {
    console.warn(`  Warning: Failed to load tools for ${serverName}: ${e}`)
    return null
  }
}

/**
 * Folder names under external/ that are imported from available-servers.ts
 * under a different server `name` (e.g. microsoft-dynamics-crm → dynamics-crm).
 */
function getExternalDirsReferencedInRegistry(): Set<string> {
  const availableServersPath = path.join(
    PLATFORM_ROOT,
    'servers/agentic/mcp/src/servers/available-servers.ts'
  )
  if (!fs.existsSync(availableServersPath)) {
    return new Set()
  }
  const src = fs.readFileSync(availableServersPath, 'utf-8')
  const dirs = new Set<string>()
  const re =
    /from\s+['"]\.\/external\/([^/'"]+)\/tools\.js['"]/g
  let m: RegExpExecArray | null
  while ((m = re.exec(src)) !== null) {
    dirs.add(m[1])
  }
  return dirs
}

/**
 * Some branches may have `external/<name>/tools.ts` without a matching
 * `available-servers.ts` row (registry drift). Include those so docs and
 * docs.json stay aligned with on-disk tools.
 */
async function appendExternalServersMissingFromRegistry(
  registryServers: ServerEntry[]
): Promise<ServerEntry[]> {
  const byName = new Set(registryServers.map((s) => s.name))
  const referencedDirs = getExternalDirsReferencedInRegistry()
  const extra: ServerEntry[] = []

  const entries = fs.readdirSync(SERVERS_DIR, { withFileTypes: true })
  for (const ent of entries) {
    if (!ent.isDirectory()) continue
    const name = ent.name
    if (byName.has(name)) continue
    if (referencedDirs.has(name)) continue

    const tools = await loadToolsForServer(name)
    if (!tools || tools.length === 0) continue

    const rawDescription = `${name.replace(/-/g, ' ')} — application MCP tools`
    extra.push({
      name,
      description: getDescription(name, rawDescription),
      path: `/${name}`,
      embedded: false,
      productionEnabled: true,
      tools
    })
    byName.add(name)
  }

  if (extra.length > 0) {
    console.log(
      `Merged ${extra.length} external server(s) not in available-servers.ts: ${extra.map((s) => s.name).join(', ')}\n`
    )
  }

  return [...registryServers, ...extra]
}

// ============================================================================
// docs.json update
// ============================================================================

function updateDocsJson(serverNames: string[], selectiveServers?: string[]): void {
  const docsJson = JSON.parse(fs.readFileSync(DOCS_JSON_PATH, 'utf-8'))

  // Find the "Application MCP Servers" group in the navigation
  let appGroup: any = null
  function findGroup(obj: any): boolean {
    if (Array.isArray(obj)) {
      for (const item of obj) {
        if (findGroup(item)) return true
      }
    } else if (obj && typeof obj === 'object') {
      if (obj.group === 'Application MCP Servers') {
        appGroup = obj
        return true
      }
      for (const value of Object.values(obj)) {
        if (findGroup(value)) return true
      }
    }
    return false
  }
  findGroup(docsJson)

  if (!appGroup) {
    console.error('Could not find "Application MCP Servers" group in docs.json')
    process.exit(1)
  }

  if (selectiveServers) {
    // Add server pages if not already present, maintaining alphabetical order
    const existingPages: string[] = appGroup.pages || []
    const serverPages = existingPages.filter(
      (p) => p !== 'api-reference/mcp-servers/application/overview'
    )
    for (const name of selectiveServers) {
      const pagePath = `api-reference/mcp-servers/application/${name}`
      if (!serverPages.includes(pagePath)) {
        serverPages.push(pagePath)
      }
    }
    serverPages.sort()
    appGroup.pages = ['api-reference/mcp-servers/application/overview', ...serverPages]
  } else {
    // Replace all pages with overview + generated pages
    const pages = ['api-reference/mcp-servers/application/overview']
    for (const name of serverNames.sort()) {
      pages.push(`api-reference/mcp-servers/application/${name}`)
    }
    appGroup.pages = pages
  }

  fs.writeFileSync(DOCS_JSON_PATH, JSON.stringify(docsJson, null, 2) + '\n')
}

// ============================================================================
// Git-based change detection
// ============================================================================

function getChangedServers(baseRef: string): string[] {
  const externalPrefix = 'servers/agentic/mcp/src/servers/external/'

  const diffOutput = execSync(
    `git diff ${baseRef} --name-only -- "${externalPrefix}"`,
    { cwd: PLATFORM_ROOT, encoding: 'utf-8' }
  ).trim()

  const serverNames = new Set<string>()
  if (diffOutput) {
    for (const filePath of diffOutput.split('\n')) {
      const relative = filePath.replace(externalPrefix, '')
      const serverName = relative.split('/')[0]
      if (serverName) {
        serverNames.add(serverName)
      }
    }
  }

  return Array.from(serverNames).sort()
}

function getNewServersWithoutDocs(externalServers: ServerEntry[]): string[] {
  const newServers: string[] = []
  
  for (const server of externalServers) {
    const docPath = path.join(OUTPUT_DIR, `${server.name}.mdx`)
    if (!fs.existsSync(docPath)) {
      newServers.push(server.name)
    }
  }
  
  return newServers.sort()
}

// ============================================================================
// Main
// ============================================================================

async function main(): Promise<void> {
  const args = process.argv.slice(2)
  const serverFlagIdx = args.indexOf('--server')
  const singleServer =
    serverFlagIdx !== -1 ? args[serverFlagIdx + 1] : undefined
  const changedFlagIdx = args.indexOf('--changed')
  const changedBaseRef =
    changedFlagIdx !== -1 ? (args[changedFlagIdx + 1] || 'origin/main') : undefined

  if (singleServer && changedBaseRef) {
    console.error('Cannot use --server and --changed together.')
    process.exit(1)
  }

  console.log('=== Application MCP Server Documentation Generator ===\n')

  // Ensure output directory exists
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true })
  }

  if (singleServer && PARTITION_DOC_SLUG_SET.has(singleServer)) {
    const family = PARTITION_FAMILIES.find((f) => f.docSlug === singleServer)
    if (!family) {
      console.error(`Unknown parent/child doc slug: ${singleServer}`)
      process.exit(1)
    }
    const ok = await syncPartitionedFamilyDocPage(family)
    if (!ok) {
      console.error(
        `No child servers found for "${family.docSlug}" under platform mcp-server-definitions`
      )
      process.exit(1)
    }
    updateDocsJson([family.docSlug], [family.docSlug])
    console.log('\n=== Done ===')
    console.log(`  Output:  ${OUTPUT_DIR}/`)
    return
  }

  // Load server registry
  let servers: ServerEntry[]
  try {
    servers = await loadAvailableServers()
    servers = await appendExternalServersMissingFromRegistry(servers)
  } catch {
    // Fallback: scan external server directories and load tools directly
    console.log('Falling back to directory-based server discovery...\n')
    servers = await fallbackLoadServers()
  }

  // Filter to external, production-enabled servers
  const externalServers = servers.filter(
    (s) => s.embedded === false && s.productionEnabled !== false
  )

  console.log(
    `Found ${externalServers.length} production-enabled application servers\n`
  )

  // Determine which servers to generate
  let toGenerate: ServerEntry[]
  let selectiveServers: string[] | undefined

  if (changedBaseRef) {
    const changedNames = getChangedServers(changedBaseRef)
    const newServerNames = getNewServersWithoutDocs(externalServers)
    const touchedPartitionSlugs = PARTITION_FAMILIES.filter((f) =>
      mcpPartitionFamilyDefinitionsChanged(changedBaseRef, f.gitDiffPathPrefix)
    ).map((f) => f.docSlug)

    // Combine changed and new servers (servers without docs)
    let allTargetNames = Array.from(
      new Set([...changedNames, ...newServerNames, ...touchedPartitionSlugs])
    ).sort()

    if (allTargetNames.length === 0) {
      console.log(
        `No external server or parent/child MCP definition changes found compared to ${changedBaseRef}, and all servers have documentation.`
      )
      console.log('\n=== Done (nothing to generate) ===')
      return
    }
    
    if (changedNames.length > 0) {
      console.log(`Changed servers (vs ${changedBaseRef}): ${changedNames.join(', ')}`)
    }
    if (newServerNames.length > 0) {
      console.log(`New servers (without documentation): ${newServerNames.join(', ')}`)
    }
    if (touchedPartitionSlugs.length > 0) {
      console.log(
        `Partitioned MCP definitions changed (vs ${changedBaseRef}): ${touchedPartitionSlugs.join(', ')}`
      )
    }
    console.log('')

    toGenerate = externalServers.filter((s) => allTargetNames.includes(s.name))
    selectiveServers = allTargetNames
    const missing = allTargetNames.filter(
      (name) => !toGenerate.some((s) => s.name === name)
    )
    if (missing.length > 0) {
      console.warn(`  Warning: changed/new but not production-enabled or not found: ${missing.join(', ')}`)
    }
  } else if (singleServer) {
    toGenerate = externalServers.filter((s) => s.name === singleServer)
    selectiveServers = [singleServer]
    if (toGenerate.length === 0) {
      console.error(`Server "${singleServer}" not found or not production-enabled.`)
      console.error(
        'Available servers:',
        externalServers.map((s) => s.name).join(', ')
      )
      process.exit(1)
    }
  } else {
    toGenerate = externalServers
  }

  let totalTools = 0
  const generatedNames: string[] = []

  for (const server of toGenerate) {
    const tools = server.tools || (await loadToolsForServer(server.name))
    if (!tools || tools.length === 0) {
      console.warn(`  Skipping ${server.name}: no tools found`)
      continue
    }

    console.log(
      `  Generating ${server.name}.mdx (${tools.length} tools)...`
    )

    const mdx = generateServerPage(server.name, server.description, tools)
    const outputPath = path.join(OUTPUT_DIR, `${server.name}.mdx`)
    fs.writeFileSync(outputPath, mdx)

    totalTools += tools.length
    generatedNames.push(server.name)
  }

  for (const family of PARTITION_FAMILIES) {
    if (
      !shouldSyncPartitionedFamily(family, { singleServer, changedBaseRef })
    ) {
      continue
    }
    const written = await syncPartitionedFamilyDocPage(family)
    if (written && !generatedNames.includes(family.docSlug)) {
      generatedNames.push(family.docSlug)
    }
  }

  generatedNames.sort((a, b) => a.localeCompare(b))

  // Update docs.json
  if (generatedNames.length > 0) {
    if (selectiveServers) {
      updateDocsJson(generatedNames, selectiveServers)
      console.log(`\nUpdated docs.json with ${generatedNames.length} page(s)`)
    } else {
      updateDocsJson(generatedNames)
      console.log(`\nUpdated docs.json with ${generatedNames.length} pages`)
    }
  }

  console.log(`\n=== Done ===`)
  console.log(`  Servers: ${generatedNames.length}`)
  console.log(`  Tools:   ${totalTools}`)
  console.log(`  Output:  ${OUTPUT_DIR}/`)
}

// Fallback: scan directories if available-servers.ts can't be imported
async function fallbackLoadServers(): Promise<ServerEntry[]> {
  // Read available-servers.ts as text and extract server configs
  const availableServersPath = path.join(
    PLATFORM_ROOT,
    'servers/agentic/mcp/src/servers/available-servers.ts'
  )
  const source = fs.readFileSync(availableServersPath, 'utf-8')

  // Find all external server directories
  const dirs = fs.readdirSync(SERVERS_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)

  const servers: ServerEntry[] = []

  for (const dirName of dirs) {
    // Extract server config from the source text
    const nameRegex = new RegExp(
      `name:\\s*'${dirName}'[\\s\\S]*?embedded:\\s*(true|false)`,
      'g'
    )
    const match = nameRegex.exec(source)
    if (!match || match[1] === 'true') continue // skip embedded or not found

    // Extract description
    const descRegex = new RegExp(
      `name:\\s*'${dirName}'[\\s\\S]*?description:[\\s\\S]*?['"\`]([^'"\`]+)['"\`]`
    )
    const descMatch = descRegex.exec(source)
    const description = descMatch ? descMatch[1] : `${dirName} API`

    // Check productionEnabled
    const prodRegex = new RegExp(
      `name:\\s*'${dirName}'[\\s\\S]*?productionEnabled:\\s*(true|false)`
    )
    const prodMatch = prodRegex.exec(source)
    const productionEnabled = prodMatch ? prodMatch[1] !== 'false' : true

    // Load tools
    const tools = await loadToolsForServer(dirName)
    if (!tools) continue

    servers.push({
      name: dirName,
      description,
      path: `/${dirName}`,
      embedded: false,
      productionEnabled,
      tools
    })
  }

  return servers
}

main().catch((e) => {
  console.error('Fatal error:', e)
  process.exit(1)
})
